clear, clc, close all
dia = load("S1.dia","-ascii");
faceMx = load("S1.fMx","-ascii");
ptCoordMx = load("S1.pMx","-ascii");
G = graph(faceMx(:,2),faceMx(:,3),dia);

plot(G,...
    'XData',ptCoordMx(:,1),...
    'YData',ptCoordMx(:,2),...
    'ZData',ptCoordMx(:,3),...
    'NodeColor','none',...
    'LineWidth',0.5*G.Edges.Weight);
axis equal